###
POST http://localhost:9000/api/restaurantes HTTP/1.1
Content-Type: application/json

{
    
    "name": "BurguerKing",
    "email": "lovojuarez10@gmail.com"
}

###
GET http://localhost:9000/api/restaurantes HTTP/1.1

###

GET http://localhost:9000/api/restaurantes/6450309827324e7ebdd2000c HTTP/1.1

###
PUT http://localhost:9000/api/restaurantes/645030a827324e7ebdd2000e HTTP/1.1
Content-Type: application/json

{
   
    "name": "WND",
    "email": "Messi10@gmail.com"
}

###
DELETE http://localhost:9000/api/restaurantes/645030a827324e7ebdd2000e HTTP/1.1